# Generated by Django 2.2.8 on 2020-09-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Medical', 'Medical'), ('Accessories', 'Accessories'), ('Furniture', 'Furniture'), ('Home Essentials', 'Home Essentials')], max_length=32)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('country_of_origin', models.CharField(blank=True, choices=[('India', 'India'), ('America', 'America'), ('Russia', 'Russia'), ('Paris', 'Paris')], max_length=32)),
                ('seller', models.CharField(max_length=32)),
                ('rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=32)),
            ],
        ),
    ]
